esphome:
  name: relay_test
  platform: ESP8266 # Change to ESP32 if using one
  board: nodemcuv2 # Adjust to match your board type

# Enable logging to monitor relay status
logger:

# Enable Home Assistant API for control
api:

# Wi-Fi setup (replace with your network details)
wifi:
  ssid: !secret wifi_ssid # WiFi SSID
  password: !secret wifi_password # WiFi password

  # Fallback hotspot in case Wi-Fi fails
  ap:
    ssid: "RelayTest Fallback"
    password: "fallback_password"

web_server:
  port: 80
  version: 2
  local: true

# Define a GPIO switch for the relay
switch:
  - platform: gpio
    name: "Test Relay"
    pin: D1 # Change to the GPIO pin your relay is connected to
    id: relay_switch
    inverted: false # Set to true if the relay operates in reverse logic

# Optional: Status LED to indicate device is running
status_led:
  pin: D2 # Change to a pin connected to an onboard LED if desired
